spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  minio:
    url: ${MINIO_URL}
    user: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    bucket: ${MINIO_BUCKET}

server:
  servlet:
    session:
      timeout: 30m